---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Reviews
- type: directory
  path: content/reviews
  label: Reviews
  create: all
  match: "**/*"
- type: heading
  label: Blog
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
- type: heading
  label: Lists
- type: directory
  path: content/lists
  label: Lists
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
