---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: content/reviews
  label: Reviews
  create: all
  match: "**/*"
  templates:
  - review-template
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
  templates:
  - blog-template
- type: directory
  path: content/lists
  label: Lists
  create: all
  match: "**/*"
  templates:
  - blog-template
upload_dir: static
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: preview
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run dev
